### ISSUE TITLE
Crash in demo project

### ISSUE THREAD

**Issue by dmitruss** [adiant/ios-sdk-objc-example#1]
![ios-sdk-objc-example xcworkspace 2016-01-21 18-16-02](https://cloud.githubusercontent.com/assets/1777197/12484391/2e32841c-c06b-11e5-8e00-9556b91d4acb.png)

**Comment by dmitruss** [comment]
Xcode Version 7.2 (7C68)

**Comment by frazjp65** [comment]
I made some changes on the ads in the ad network. Is this still a problem for you?

**Comment by frazjp65** [comment]
This should be fixed with my change last month and the latest version.
